#!/bin/bash 
autoMuteStatus=$(/usr/bin/amixer sget --card 1 "Auto-Mute Mode" Disabled | grep Item0 | cut -d ":" -f 2 | tr -d "'" | tr -d " ")

[ $autoMuteStatus == "Disabled" ] && /usr/bin/amixer sset --card 1 "Auto-Mute Mode" Enabled || /usr/bin/amixer sset --card 1 "Auto-Mute Mode" Disabled
